apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.aspnetcoreEnv }}

---
apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
type: Opaque
data:
  CONNECTION_STRING: {{ printf "Host=%s;Port=%s;Database=%s;Username=%s;Password=%s;" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.database .Values.postgresql.username .Values.postgresql.password | b64enc | quote }}
