apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity-api.fullname" . }}
  labels:
    {{- include "identity-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "identity-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "identity-api.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              port: {{ .Values.probes.liveness.port }}
              path: {{ .Values.probes.liveness.path }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}  
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              port: {{ .Values.probes.readiness.port }}
              path: {{ .Values.probes.readiness.path }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: CONNECTION_STRING
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: identity-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: identity-config
                  key: VERSION
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
