# This helm values file defines all infrastructure used by eShopOnContainers.
# It is used on all charts, so ** MUST BE INCLUDED ** on every deployment

inf:
  sql: # inf.sql defines the sql server databases & logins
    #    host:  my-sql-server   # Uncomment to specify a custom sql-server to be used. By default "sql-data-<appname>" will be used
    common:
      user: sa # SQL user
      pwd: Pass@word # SQL pwd
      pid: Developer
    ordering: # inf.sql.ordering: settings for the ordering-api sql (user, pwd, db)
      db: OrderingDb # Ordering API SQL db name
