{{- $name := include "ordering-migrator.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ordering-migrator.fullname" . }}
  labels:
    app: {{ template "ordering-migrator.name" . }}
    chart: {{ template "ordering-migrator.chart" . }}
    release: {{ .Release.Name }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: {{ template "ordering-migrator.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{- .Values.image.repository -}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.env.configmap -}}
          {{- range .Values.env.configmap }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $cfgname }}
                  key: {{ .key }}
          {{- end -}}
          {{- end }}
          command: ["dotnet"]
          args: ["Ordering.Migrator.dll", "-q"]
